### ISSUE TITLE
Implement design

### ISSUE THREAD

**Issue by adriaandotcom** [BustByte/coronastatus.no#191] opened 2020-03-21 23:02 UTC
> @michaelmcmillan: i think we have a couple of designers in the norwegian gang that has some good ideas as well, can let them go over the figma first? :) - https://t.me/onzecorona/514

Are there any comments from the designers in the norwegian gang before we can start implementing this design?

https://www.figma.com/file/WriP7XWOZbni3X94J0asVX/Tailwind-CSS-UI?node-id=6020%3A543

<kbd><img height="500px" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/77238455-7182f980-6bd0-11ea-89b2-2175b259d2fc.jpg"></kbd>

**Comment by gavinhewitt** [comment] 2020-03-21 23:07
I'd say it's a bit too colourful/frivolous for my taste. Personally I don't see anything wrong with the current design.

**Comment by willwillems** [comment] 2020-03-22 08:52
I could implement the design in a couple of hours but I would be good to know if it's final.

**Comment by fossecode** [comment] 2020-03-22 10:09
Got this comment from one of the Norwegian designers:
> I suddenly became a little unsure of the design above. Seems it is a little too "colorful" in a sense, too little serious.

As briefly discussed in Telegram, we should also consider clearifying our value prop and implement a clearer call to action.

**Comment by amritnagi** [comment] 2020-03-22 12:52
If the issue is the colour, the icons are also available in a single colour.

https://www.iconfinder.com/iconsets/coronavirus-glyph

The design definitely wasn't intended to be frivolous or not a serious matter, so I apologise if anyone feels that was it is.

My intention was to try and create something friendly and less "formal/scientific". With all of the advice and reading people have been doing, I figured going more visual would be a bit of a change.

Plus I thought it might help to draw people in, keep their attention and most importantly complete the form.

I'm totally fine if you don't use it or if you want to change it 👍🏼

**Comment by adriaandotcom** [comment] 2020-03-22 12:57
I'm highly in favor of changing the design because people take it more seriously if it looks better. It's maybe not the most important thing (that's getting it out there), but I think it important enough so people want to share it more. What if we make the design a bit less playful?

**Comment by fossecode** [comment] 2020-03-22 13:01
Totally agree @adriaanvanrossum. It would be great if you could make it a little bit less playful and maybe see how it looks with another color palette.

**Comment by willwillems** [comment] 2020-03-22 13:02
I fully agree with @adriaanvanrossum, I think design here is quite important. If it looks better it conveys authority and that we're serious about this.

@amritnagi I really like the color icons, how about just changing the purple to a light orange/yellow?

**Comment by amritnagi** [comment] 2020-03-22 13:09
Cool, I'll try a few ideas... Totally happy to give edit rights to anyone if they want to create alternatives?

Won't be until the evening once the kids are asleep.... Having all the fun keeping 4yo twins entertained 🤣

**Comment by adriaandotcom** [comment] 2020-03-22 13:27
I think that would be great.

**Comment by willwillems** [comment] 2020-03-23 08:29
@adriaanvanrossum I'm free to do the design right now if that's what we want, if I remeber everyone was pretty enthousiastic about the green design?

**Comment by amritnagi** [comment] 2020-03-23 08:38
@NickolasBoyer Awesome! Let me know if you need a hand... Prob won't be able to help until the evening though.

Just little note, the spacing and positioning is a bit rough, I didn't have time to tighten it all up, so just use it as a rough guideline. Feel free to improve where applicable.

Are you planning on using tailwind css?

**Comment by adriaandotcom** [comment] 2020-03-23 08:44
Green design was in favor indeed! Let me know if you need anything. I can also help if you have the base ready.

**Comment by willwillems** [comment] 2020-03-23 09:12
> @NickolasBoyer Awesome! Let me know if you need a hand... Prob won't be able to help until the evening though.
> 
> Just little note, the spacing and positioning is a bit rough, I didn't have time to tighten it all up, so just use it as a rough guideline. Feel free to improve where applicable.
> 
> Are you planning on using tailwind css?

No worries because I'm indeed using Tailwind so everything will pretty much fall into place.

I do not want to step on anyone's toes here, or make the project harder for people to contribute to but what do we think about separating the FE from the BE? It might be more convenient once we start getting some traffic to have the FE as static assests, and it makes it more maintainable and easier to work on for different people.

Anyway I'm on it RN!

**Comment by amritnagi** [comment] 2020-03-23 09:24
@adriaanvanrossum will probably be able to clarify that!

@NickolasBoyer Drop me a message on telegram if you want to discuss the page / need another set of eyes for feedback etc 👍

**Comment by adriaandotcom** [comment] 2020-03-23 09:28
@NickolasBoyer I think for now we don’t have time for rewriting it to FE and BE. Let’s first make it popular and focus on new features first. It’s not a complicated app and until now it worked great with multiple people contributing. If this gets annoying then we can always separate them.

Love that you are working on the designs! Thanks a lot.

**Comment by fossecode** [comment] 2020-03-23 09:44
Although it might not scale that well, using ejs and MVC allows us to move really fast, so I am also in favor of keeping it that way for now.

**Comment by willwillems** [comment] 2020-03-23 10:29
@amritnagi do you have those Corona Glyphs somewhere in color?

**Comment by amritnagi** [comment] 2020-03-23 10:31
@NickolasBoyer Here you go:
https://www.iconfinder.com/iconsets/coronavirus-flat

**Comment by willwillems** [comment] 2020-03-23 11:10
Thanks @amritnagi !

**Comment by adriaandotcom** [comment] 2020-03-23 11:13
@NickolasBoyer merged [a PR](https://github.com/BustByte/coronastatus/pull/230) that has a little bit of impact on the home page and profile page. So you might want to merge master into your branch.

**Comment by willwillems** [comment] 2020-03-23 11:49
@adriaanvanrossum no worries, I'm working on the FE separately for now and I'll integrate it in the main project when it is done so don't be afraid to change things around!

You can follow the FE progress here and feedback is welcome:

https://unruffled-ride-0e7055.netlify.com/

I'll try to update it occasionally. Keep in mind I'm not working through it linearly so if it doesn't match the design yet it probably will later on.

Cheers!

**Comment by michaelmcmillan** [comment] 2020-03-23 17:04
Anything I can assist with here @NickolasBoyer?

**Comment by willwillems** [comment] 2020-03-23 17:06
@michaelmcmillan yes absolutely! I'll throw you in the design telegram group, we still need a few things to be done!

**Comment by willwillems** [comment] 2020-03-23 17:09
@michaelmcmillan we're working on the design here: https://github.com/BustByte/coronastatus/tree/implement-design we still need to make it responsive and the stats page and privacy page still need to be done, could you @ @adriaanvanrossum in the main telegram about this?

**Comment by Kilian** [comment] 2020-03-25 12:53
since this is done, let's close it and keep the issue list as small and up-to-date as possible.

**Closed as completed by Kilian** 2020-03-25 12:53 UTC
Labels: design, marketing
